AWSTemplateFormatVersion: "2010-09-09"
Description: "HostedZone"

Parameters:
  SystemCode:
    Type: "String"
    Default: "email-uploader"
  SystemEnv:
    Type: "String"
  DomainName:
    Type: String
    Description: "The domain name for the hosted zone (e.g., example.com)"

Resources:
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref DomainName

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub "hostedzone-${SystemCode}-${SystemEnv}-id"
  HostedZoneNs:
    Value: !Join [ ",", !GetAtt HostedZone.NameServers ]
    Export:
      Name: !Sub "hostedzone-${SystemCode}-${SystemEnv}-ns"
  HostedZoneName:
    Value: !Ref DomainName
    Export:
      Name: !Sub "hostedzone-${SystemCode}-${SystemEnv}-name"

