AWSTemplateFormatVersion: "2010-09-09"
Description: "EventBridge and Lambda with IAMRole"

Parameters:
  SystemCode:
    Type: "String"
    Default: "email-uploader"
  SystemEnv:
    Type: "String"

Resources:
  LogsLogGroupLambdaSesFileUpload:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/lambda-${SystemCode}-${SystemEnv}-file-upload"
      RetentionInDays: 30

  IAMRoleLambdaSesFileUpload:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "role-${SystemCode}-${SystemEnv}-file-upload-lambda"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3EventPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - { Fn::ImportValue: !Sub "s3-${SystemCode}-${SystemEnv}-ses-arn" }
                  - { Fn::ImportValue: !Sub "s3-${SystemCode}-${SystemEnv}-ses-arn" }

  LambdaFunctionSesFileUpload:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Sub "lambda-${SystemCode}-${SystemEnv}-file-upload"
      Handler: index.handler
      Role: !GetAtt IAMRoleLambdaSesFileUpload.Arn
      Runtime: python3.13
      Code:
        ZipFile: |
          def handler(event, context):
              print("hello world")

  EventsRuleSesS3FileCreated:
    Type: "AWS::Events::Rule"
    Properties:
      Name: !Sub "events-${SystemCode}-${SystemEnv}-file-created"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - { Fn::ImportValue: !Sub "s3-${SystemCode}-${SystemEnv}-ses" }
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunctionSesFileUpload.Arn
          Id: TargetLambda

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref LambdaFunctionSesFileUpload
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventsRuleSesS3FileCreated.Arn
